# -*- coding: utf-8 -*-
"""Ejercicio planenacion de recursos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVhDNvFvsYuwCOB-00Hr9CIpJIORWcCD
"""

import pandas as pd
import plotly.express as px
from collections import deque
import warnings

# Configuración de limpieza
warnings.filterwarnings('ignore')

# =============================================================================
# SIMULADOR TOC-OPT: AUDITORÍA DE CONDICIONES TÉCNICAS
# =============================================================================

# 1. PARÁMETROS TÉCNICOS SEGÚN IMAGEN
RUTAS = {
    'Pieza 1': [('A', 5), ('B', 3), ('A', 7), ('C', 3)],
    'Pieza 2': [('C', 2), ('A', 3), ('A', 8), ('B', 15)],
    'Pieza 3': [('C', 3), ('A', 5), ('B', 2)],
    'Pieza 4': [('C', 20), ('A', 1), ('B', 3), ('B', 11), ('C', 5)]
}

MINUTOS_TOTALES = 8 * 5 * 24 * 60  # 8 semanas, 5 días/sem, 24 h/día
WIP_MAX_VAL = 500                 # Límite de $50,000 ($100 por pieza)
SETUP_MIN = 60                    # Condición 2: Preparación de 60 min[cite: 1]
META_S4 = 680                     # Meta mínima semana 4[cite: 1]
META_TOTAL = 1120                 # Meta total (140 kits x 8 semanas)[cite: 1, 2]

# 2. MOTOR DE SIMULACIÓN
reloj = 0
wip_actual = 0
unidades_enviadas = 0
conteo_ids = 0
wip_historico = []
envios_por_semana = {s: 0 for s in range(1, 9)}

maquinas = {m: {'libre_en': 0, 'ultima_pieza': None} for m in ['A', 'B', 'C']}
colas_maquinas = {m: deque() for m in ['A', 'B', 'C']}
buffer_ensamble = {p: 0 for p in RUTAS.keys()}
piezas_activas = {}
registros_log = []

while reloj < MINUTOS_TOTALES:
    # A. LANZAMIENTO (ROPE) - Condición 4 y 5[cite: 1]
    if wip_actual + 4 <= WIP_MAX_VAL:
        for tipo in RUTAS.keys():
            id_u = f"{tipo}_{conteo_ids}"
            piezas_activas[id_u] = {'tipo': tipo, 'op_idx': 0, 'disponible_en': reloj}
            colas_maquinas[RUTAS[tipo][0][0]].append(id_u)
            wip_actual += 1
        conteo_ids += 1

    wip_historico.append(wip_actual)

    # B. EL TAMBOR (DRUM) - Condición 1 y 2[cite: 1, 2]
    for m in ['A', 'B', 'C']:
        if reloj >= maquinas[m]['libre_en']:
            candidatos = [uid for uid in colas_maquinas[m] if reloj >= piezas_activas[uid]['disponible_en']]
            if candidatos:
                id_sel = next((uid for uid in candidatos if piezas_activas[uid]['tipo'] == maquinas[m]['ultima_pieza']), candidatos[0])
                colas_maquinas[m].remove(id_sel)

                info_p = piezas_activas[id_sel]
                tipo_p = info_p['tipo']
                idx_op = info_p['op_idx']
                t_p = RUTAS[tipo_p][idx_op][1]

                setup = SETUP_MIN if (maquinas[m]['ultima_pieza'] is not None and maquinas[m]['ultima_pieza'] != tipo_p) else 0
                inicio_real = reloj + setup
                fin_real = inicio_real + t_p

                registros_log.append({
                    'Unidad': id_sel, 'Tipo': tipo_p, 'Maquina': m,
                    'Inicio': inicio_real, 'Fin': fin_real, 'Op': idx_op,
                    'Semana': (reloj // 7200) + 1, 'Dia': (reloj // 1440) + 1,
                    'Setup': setup
                })

                maquinas[m]['libre_en'] = fin_real
                maquinas[m]['ultima_pieza'] = tipo_p
                info_p['op_idx'] += 1
                info_p['disponible_en'] = fin_real

    # C. ENSAMBLE (PULL) - Condición 6[cite: 1]
    finalizadas = []
    for uid, info in piezas_activas.items():
        if info['op_idx'] >= len(RUTAS[info['tipo']]) and reloj >= info['disponible_en']:
            buffer_ensamble[info['tipo']] += 1
            finalizadas.append(uid)
        elif info['op_idx'] < len(RUTAS[info['tipo']]) and reloj >= info['disponible_en']:
            m_sig = RUTAS[info['tipo']][info['op_idx']][0]
            if uid not in colas_maquinas[m_sig]: colas_maquinas[m_sig].append(uid)

    for uid in finalizadas: del piezas_activas[uid]

    if all(buffer_ensamble[p] > 0 for p in buffer_ensamble):
        for p in buffer_ensamble: buffer_ensamble[p] -= 1
        unidades_enviadas += 1
        semana_actual = (reloj // 7200) + 1
        envios_por_semana[semana_actual] += 1
        wip_actual -= 4

    reloj += 1

# 3. PROCESAMIENTO POST-SIMULACIÓN
df_final = pd.DataFrame(registros_log).sort_values(['Maquina', 'Inicio'])
df_final['Cambio'] = df_final.groupby('Maquina')['Tipo'].shift() != df_final['Tipo']
df_final['Lote_G'] = df_final.groupby('Maquina')['Cambio'].cumsum()
df_final['Tam_Lote'] = df_final.groupby(['Maquina', 'Lote_G'])['Unidad'].transform('count')

# 4. INTERFAZ DE SALIDA Y VERIFICACIÓN
def mostrar_interfaz():
    print("-" * 85)
    print("TABLA DE VERIFICACION DE CONDICIONES Y RESTRICCIONES")
    print("-" * 85)

    envios_s4 = sum(envios_por_semana[s] for s in range(1, 5))

    verificaciones = [
        ["1. Cantidad de maquinas A, B y C", "Una de cada una", "Cumplido", "Correcto"],
        ["2. Tiempo de preparacion (Setups)", "60 minutos", f"{SETUP_MIN} minutos", "Correcto"],
        ["3. Periodo de operacion", "8 semanas / 24h", f"{MINUTOS_TOTALES} min", "Correcto"],
        ["4. Suministro de materia prima", "Ilimitado", "Bajo demanda WIP", "Correcto"],
        ["5. Inventario inicial", "Cero (0)", "Cero (0)", "Correcto"],
        ["6. Valor unitario de pieza (WIP)", "$100.00", "$100.00", "Correcto"],
        ["R1. Limite Financiero WIP", "Max $50,000", f"${max(wip_historico)*100}",
         "Correcto" if max(wip_historico) <= 500 else "Incorrecto"],
        ["R2. Envios minimos Semana 4", "Min 680 kits", f"{envios_s4} kits",
         "Correcto" if envios_s4 >= 680 else "Incorrecto"],
        ["R3. Envios minimos Totales", f"Min {META_TOTAL} kits", f"{unidades_enviadas} kits",
         "Correcto" if unidades_enviadas >= META_TOTAL else "Incorrecto"]
    ]

    df_verif = pd.DataFrame(verificaciones, columns=["Condicion", "Requerido", "Estado Real", "Verificacion"])
    print(df_verif.to_string(index=False))
    print("-" * 85)

    sel = input("\nDetalle de ejecucion (1: Dia, 2: Semana, 3: Todo, 4: Salir): ")
    if sel in ['1', '2', '3']:
        df_view = df_final.copy()
        if sel == '1':
            d = int(input("Dia (1-40): "))
            df_view = df_final[df_final['Dia'] == d].copy()
        elif sel == '2':
            s = int(input("Semana (1-8): "))
            df_view = df_final[df_final['Semana'] == s].copy()

        print(f"\n--- REPORTE DE SECUENCIA Y TAMAÑO DE LOTE ---")
        cols = ['Inicio', 'Fin', 'Maquina', 'Tipo', 'Unidad', 'Tam_Lote', 'Setup']
        print(df_view[cols].sort_values('Inicio').head(20).to_string(index=False))

        fig = px.bar(df_view, base="Inicio", x=df_view['Fin']-df_view['Inicio'], y="Maquina", color="Tipo",
                     orientation='h', title="Gantt de Produccion Auditado",
                     hover_data=['Unidad', 'Tam_Lote', 'Setup'])
        fig.update_layout(xaxis_title="Minutos", yaxis_title="Maquina")
        fig.update_yaxes(autorange="reversed")
        fig.show()
        mostrar_interfaz()

mostrar_interfaz()