# -*- coding: utf-8 -*-
"""Ejercicio universidades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kyq-Vq-ciqG1JblNCQvoeVyvn8M5kKgd
"""

#análisis exploratorio de datos
#cargar lib pandas
import pandas as pd
# cargar en data frame el archivo csv
datos = pd.read_csv("cwurDataV1.csv")
print(datos)
#___________________________
#consistencia de los valores erróneos...
#ciclo for
for puntaje in datos.iterrows():
  index_value, column_values = puntaje
  array1 = float(column_values['score'])
  if array1 < 0:
   array1 *= -1
  datos.at[index_value, 'score'] = array1
#print(datos)

#datos atipicos

ValorMin = 2012
ValorMax = 2015
arrayPrevio = ValorMin
for anio in datos.iterrows():
  index_value, column_values = anio
  array1 = int(column_values['year'])
  if array1 < ValorMin or array1 > ValorMax:
    array1 = arrayPrevio
    datos.at[index_value, 'year'] = array1
  arrayPrevio = array1

#print(datos)

#datos nulos
#deteccion
#print(datos.isnull().sum())

print(datos['broad_impact'].mean())
print(datos['broad_impact'].median())
print(datos['broad_impact'].mode())
##############################################################
#Darle consistencia valores nuños del campo "factor de impacto" por el valor de la mediana

datos['broad_impact'] = datos['broad_impact'].fillna(datos['broad_impact'].median())
print(datos)

#convertir campo factor de impacto a dato entero
datos['broad_impact'] = datos['broad_impact'].astype('int64')
print(datos)

#copia de coherencia

#crear backup

datos.to_csv('cwurDataPreparado.csv', index = False)