# -*- coding: utf-8 -*-
"""optimizacion con toc .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Avm5_mLSzpp2BEGb5PSQOD2fKFhQRmeP
"""

# ═══════════════════════════════════════════════════════════════════════════
#  CÓDIGO 1: SOLVER MIP
#  Teoría de Restricciones — Problema Goldratt
#  Herramienta: PuLP + CBC
#
#  Datos validados en informe teórico:
#    - Cuello de botella: Máquina B (34 min/ud, 206 ud/semana)
#    - Lotes iguales 1:1:1:1 (P1=P2=P3=P4 por requisito de ensamble)
#    - Setups fijos por semana: A=4, B=3, C=4 (estrategia lote puro)
#    - Piso mínimo S1-S3: 158 ud/sem (por restricción acumulado S4)
#    - WIP máximo: 500 piezas = $50.000
# ═══════════════════════════════════════════════════════════════════════════

import pulp
import time

# ── 1. PARÁMETROS ─────────────────────────────────────────────────────────

SEMANAS  = 8
PIEZAS   = [1, 2, 3, 4]
MAQUINAS = ['A', 'B', 'C']

CAP    = 7_200   # min/semana por máquina (5 días × 24 h × 60 min)
SS     = 60      # min por setup (cambio de tipo de operación)
WMAX   = 500     # piezas máx. en WIP ($50.000 / $100 por pieza)
DMIN   = 140     # unidades mínimas enviadas por semana
DACUM4 = 680     # unidades acumuladas mínimas al final de semana 4

# T_ij: tiempo total de Pieza i en Máquina j (min/ud) — verificado
T = {
    (1,'A'): 12,  (1,'B'):  3,  (1,'C'):  3,
    (2,'A'): 11,  (2,'B'): 15,  (2,'C'):  2,
    (3,'A'):  5,  (3,'B'):  2,  (3,'C'):  3,
    (4,'A'):  1,  (4,'B'): 14,  (4,'C'): 25,
}

# Setups por semana por máquina (si se producen las 4 piezas)
NS = {'A': 4, 'B': 3, 'C': 4}

# Carga total por máquina (min/ud) = suma T_ij sobre todas las piezas
carga = {j: sum(T[i, j] for i in PIEZAS) for j in MAQUINAS}
# → A=29, B=34, C=33

# Capacidad neta por semana = CAP - setups * SS
cap_neta = {j: CAP - NS[j] * SS for j in MAQUINAS}
# → A=6.960, B=7.020, C=6.960

# Unidades máximas por semana limitadas por cada máquina
uds_max = {j: cap_neta[j] // carga[j] for j in MAQUINAS}
# → A=240, B=206, C=210 → cuello de botella: B

# ── 2. MODELO MIP ─────────────────────────────────────────────────────────
#
# Simplificación válida:
#   lote_s = unidades de CADA pieza producidas en semana s
#   (lotes iguales para las 4 piezas por proporción 1:1:1:1 del ensamble)
#   inv_(i,s) = inventario de Pieza i al final de semana s
#   x_s = unidades terminadas enviadas en semana s

m = pulp.LpProblem("TOC_OPT_MIP", pulp.LpMaximize)
S = range(1, SEMANAS + 1)

# Variables de decisión
x    = {s: pulp.LpVariable(f"x_{s}",    lowBound=0, cat='Integer') for s in S}
lote = {s: pulp.LpVariable(f"lote_{s}", lowBound=0, cat='Integer') for s in S}
inv  = {(i, s): pulp.LpVariable(f"inv_{i}_{s}", lowBound=0, cat='Integer')
        for i in PIEZAS for s in S}

# FUNCIÓN OBJETIVO: MAX Z = Σ x_s
m += pulp.lpSum(x[s] for s in S), "Z_total_unidades"

# R1 — Balance de inventario por pieza
# inv_(i,s) = inv_(i,s-1) + lote_s - x_s    ∀ i, s
# (mismo lote para las 4 piezas; x_s consume 1 de cada tipo)
for i in PIEZAS:
    for s in S:
        inv_prev = inv[(i, s - 1)] if s > 1 else 0
        m += inv[(i, s)] == inv_prev + lote[s] - x[s], f"R1_bal_P{i}_S{s}"

# R3 — Capacidad de máquinas (procesamiento + setups fijos por semana)
# carga_j × lote_s + NS_j × SS ≤ CAP    ∀ j, s
for j in MAQUINAS:
    for s in S:
        m += carga[j] * lote[s] + NS[j] * SS <= CAP, f"R3_cap_{j}_S{s}"

# R5 — WIP máximo 500 piezas en cualquier semana
# Σ_i inv_(i,s) ≤ 500    ∀ s
for s in S:
    m += pulp.lpSum(inv[(i, s)] for i in PIEZAS) <= WMAX, f"R5_wip_S{s}"

# R6 — Envíos mínimos semanales
# x_s ≥ 140    ∀ s
for s in S:
    m += x[s] >= DMIN, f"R6_min_S{s}"

# R7 — Acumulado mínimo semana 4
# Σ_{s=1..4} x_s ≥ 680
m += pulp.lpSum(x[s] for s in range(1, 5)) >= DACUM4, "R7_acum_S4"

# ── 3. RESOLUCIÓN ─────────────────────────────────────────────────────────

print("=" * 65)
print("  CASO TOC-OPT — SOLVER MIP")
print("  Teoría de Restricciones — Problema Goldratt")
print("=" * 65)
print(f"\n  Parámetros clave:")
print(f"  {'Máquina':<10} {'Carga (min/ud)':<18} {'Setups/sem':<14} {'Uds.máx/sem'}")
for j in MAQUINAS:
    tag = " Confirmación Cuello De Botella" if j == 'B' else ""
    print(f"  {j:<10} {carga[j]:<18} {NS[j]:<14} {uds_max[j]}{tag}")
print(f"\n  Variables:      {len(m.variables())}")
print(f"  Restricciones:  {len(m.constraints)}")
print(f"\n  eb proceso")

t0     = time.time()
status = m.solve(pulp.PULP_CBC_CMD(msg=0, timeLimit=60))
tf     = time.time() - t0

print(f"  Estado: {pulp.LpStatus[m.status]}  |  Tiempo: {tf:.2f} s")

if pulp.LpStatus[m.status] not in ['Optimal', 'Feasible']:
    print("\n No se encontró solución factible. Verificar restricciones.")
    exit()

# ── 4. EXTRACCIÓN DE VALORES ──────────────────────────────────────────────

Z     = int(pulp.value(m.objective))
x_v   = {s: int(pulp.value(x[s])    or 0) for s in S}
lot_v = {s: int(pulp.value(lote[s]) or 0) for s in S}
inv_v = {(i, s): int(pulp.value(inv[(i, s)]) or 0) for i in PIEZAS for s in S}

# ── 5. TABLA DE RESULTADOS ────────────────────────────────────────────────

sep = "─" * 80

print(f"\n{'='*65}")
print(f"  SOLUCIÓN ÓPTIMA — Z* = {Z} unidades enviadas en 8 semanas")
print(f"{'='*65}")

print(f"\n{sep}")
print(f"  {'Sem':>3} | {'Lote':>5} | {'Enviadas':>8} | {'Acumulado':>9} | "
      f"{'WIP':>5} | {'Valor WIP':>10} | {'%A':>5} | {'%B':>5} | {'%C':>5}")
print(sep)

acum = 0
for s in S:
    acum   += x_v[s]
    wip     = sum(inv_v[(i, s)] for i in PIEZAS)
    val_wip = wip * 100

    uso = {j: carga[j] * lot_v[s] + NS[j] * SS for j in MAQUINAS}
    pct = {j: uso[j] / CAP * 100 for j in MAQUINAS}

    r6_ok = "cumple" if x_v[s] >= DMIN else "no cumple"
    print(f"  {s:>3} | {lot_v[s]:>5} | {x_v[s]:>7} {r6_ok} | {acum:>9} | "
          f"{wip:>5} | ${val_wip:>9,.0f} | {pct['A']:>4.1f}% | {pct['B']:>4.1f}% | {pct['C']:>4.1f}%")

print(sep)

# ── 6. VERIFICACIÓN DE RESTRICCIONES ─────────────────────────────────────

acum4   = sum(x_v[s] for s in range(1, 5))
wip_max = max(sum(inv_v[(i, s)] for i in PIEZAS) for s in S)
min_sem = min(x_v.values())
max_sem = max(x_v.values())
min_s13 = min(x_v[s] for s in range(1, 4))

print(f"\n{'─'*50}")
print("  VERIFICACIÓN DE RESTRICCIONES")
print(f"{'─'*50}")

checks = [
    ("R3 Cap. B (peor semana)",
     f"{max(carga['B']*lot_v[s]+NS['B']*SS for s in S)} min",
     max(carga['B']*lot_v[s]+NS['B']*SS for s in S) <= CAP,
     f"≤ {CAP}"),
    ("R5 WIP máximo",    f"{wip_max} piezas", wip_max  <= WMAX,   f"≤ {WMAX}"),
    ("R6 Mín. semanal",  f"{min_sem} ud/sem", min_sem  >= DMIN,   f"≥ {DMIN}"),
    ("R7 Acumulado S4",  f"{acum4} ud",        acum4    >= DACUM4, f"≥ {DACUM4}"),
    ("TOC: Piso S1-S3",  f"{min_s13} ud/sem", min_s13  >= 158,    "≥ 158"),
]
for nombre, valor, ok, req in checks:
    print(f"  {'Cumple' if ok else 'No cumple'}  {nombre:<26} {valor:<16} (req: {req})")

# ── 7. RESUMEN EJECUTIVO ──────────────────────────────────────────────────

util_B_prom = sum(carga['B']*lot_v[s] + NS['B']*SS for s in S) / (CAP * SEMANAS) * 100
util_A_prom = sum(carga['A']*lot_v[s] + NS['A']*SS for s in S) / (CAP * SEMANAS) * 100
util_C_prom = sum(carga['C']*lot_v[s] + NS['C']*SS for s in S) / (CAP * SEMANAS) * 100

print(f"\n{'─'*50}")
print("  RESUMEN ")
print(f"{'─'*50}")
print(f"  Unidades totales (Z*):         {Z} ud")
print(f"  Promedio semanal:              {Z/SEMANAS:.1f} ud/sem")
print(f"  Acumulado semana 4:            {acum4} ud")
print(f"  WIP máximo alcanzado:          {wip_max} piezas (${wip_max*100:,})")
print(f"  Mínimo semanal enviado:        {min_sem} ud (semana {[s for s in S if x_v[s]==min_sem][0]})")
print(f"  Máximo semanal enviado:        {max_sem} ud")
print(f"  Utilización promedio Máq. A:   {util_A_prom:.1f}%")
print(f"  Utilización promedio Máq. B:   {util_B_prom:.1f}%  cuello de botella")
print(f"  Utilización promedio Máq. C:   {util_C_prom:.1f}%")
print(f"  Setups totales (8 semanas):    {sum(NS[j] for j in MAQUINAS)*SEMANAS} ({NS['A']*SEMANAS}A + {NS['B']*SEMANAS}B + {NS['C']*SEMANAS}C)")
print(f"{'─'*50}")

import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime, timedelta

# =================================================================
# 1. PARÁMETROS TÉCNICOS (Basado en cccc.pdf)
# =================================================================
OPERACIONES = {
    'P1': [('A', 5), ('B', 3), ('A', 7), ('C', 3)],
    'P2': [('C', 2), ('A', 3), ('A', 8), ('B', 15)],
    'P3': [('C', 3), ('A', 5), ('B', 2)],
    'P4': [('C', 20), ('A', 1), ('B', 3), ('B', 11), ('C', 5)]
}

HORIZONTE_MINUTOS = 57600
MAX_WIP = 500
SETUP_TIME = 60

class MotorSimulacionTOC:
    def __init__(self, meta_semanal=206):
        self.reloj = 0
        self.meta_semanal = meta_semanal
        self.maquinas = {m: {'libre_en': 0, 'setup_actual': None, 'tarea_actual': None} for m in ['A', 'B', 'C']}
        self.colas = {m: [] for m in ['A', 'B', 'C']}
        self.piezas_en_sistema = []
        self.almacen_ensamble = {p: 0 for p in ['P1', 'P2', 'P3', 'P4']}
        self.unidades_enviadas = 0
        self.registros_gantt = []
        self.wip_historico = []
        self.piezas_lanzadas_semana = {p: 0 for p in ['P1', 'P2', 'P3', 'P4']}

    def ejecutar(self):
        while self.reloj < HORIZONTE_MINUTOS:
            semana_actual = (self.reloj // 7200) + 1

            # 1. Cuerda (Rope): Lanzamiento controlado
            for p_tipo in ['P1', 'P2', 'P3', 'P4']:
                if len(self.piezas_en_sistema) < MAX_WIP and self.piezas_lanzadas_semana[p_tipo] < self.meta_semanal:
                    nueva_pieza = {'tipo': p_tipo, 'op_idx': 0, 'id': f"{p_tipo}_{self.reloj}_{len(self.piezas_en_sistema)}"}
                    self.piezas_en_sistema.append(nueva_pieza)
                    self.piezas_lanzadas_semana[p_tipo] += 1
                    self.colas[OPERACIONES[p_tipo][0][0]].append(nueva_pieza)

            if self.reloj > 0 and self.reloj % 7200 == 0:
                self.piezas_lanzadas_semana = {p: 0 for p in ['P1', 'P2', 'P3', 'P4']}

            # 2. Despacho (Tambor)
            for m_id in ['B', 'A', 'C']:
                m_info = self.maquinas[m_id]
                if self.reloj >= m_info['libre_en'] and self.colas[m_id]:
                    # Priorizar mismo setup para evitar los 60 min
                    pieza = next((p for p in self.colas[m_id] if p['tipo'] == m_info['setup_actual']), self.colas[m_id][0])
                    self.colas[m_id].remove(piece := pieza)

                    setup_req = SETUP_TIME if piece['tipo'] != m_info['setup_actual'] and m_info['setup_actual'] is not None else 0
                    t_proc = OPERACIONES[piece['tipo']][piece['op_idx']][1]

                    m_info['libre_en'] = self.reloj + setup_req + t_proc
                    m_info['setup_actual'], m_info['tarea_actual'] = piece['tipo'], piece

                    self.registros_gantt.append({
                        'Machine': f"Máquina {m_id}", 'Task': f"{piece['id']}", 'Piece': piece['tipo'],
                        'Start': self.reloj, 'Finish': self.reloj + setup_req + t_proc,
                        'Week': semana_actual, 'Is_Setup': setup_req > 0
                    })

            # 3. Movimiento (Transferencia = 1)
            for m_id, m_info in self.maquinas.items():
                if m_info['tarea_actual'] and self.reloj == m_info['libre_en'] - 1:
                    p = m_info['tarea_actual']
                    p['op_idx'] += 1
                    m_info['tarea_actual'] = None
                    if p['op_idx'] < len(OPERACIONES[p['tipo']]):
                        self.colas[OPERACIONES[p['tipo']][p['op_idx']][0]].append(p)
                    else:
                        self.almacen_ensamble[p['tipo']] += 1
                        self.piezas_en_sistema.remove(p)

            # 4. Ensamble
            while all(self.almacen_ensamble[p] > 0 for p in ['P1', 'P2', 'P3', 'P4']):
                for p in ['P1', 'P2', 'P3', 'P4']: self.almacen_ensamble[p] -= 1
                self.unidades_enviadas += 1

            if self.reloj % 60 == 0: self.wip_historico.append(len(self.piezas_en_sistema))
            self.reloj += 1

# =================================================================
# 2. EJECUCIÓN Y MENÚ DE SALIDA
# =================================================================
sim = MotorSimulacionTOC()
print("Simulando 8 semanas de producción... por favor espere.")
sim.ejecutar()

df_gantt = pd.DataFrame(sim.registros_gantt)

def mostrar_menu():
    print("\n" + "="*50)
    print("      SISTEMA DE CONTROL DE PRODUCCIÓN TOC")
    print("="*50)
    print(f"Total unidades enviadas: {sim.unidades_enviadas}")
    print(f"WIP máximo: {max(sim.wip_historico)} piezas ($ {max(sim.wip_historico)*100})")
    print("-" * 50)

    while True:
        try:
            opcion = input("\nIngrese la SEMANA a visualizar (1-8) o 'S' para salir: ").upper()
            if opcion == 'S':
                print("Proceso finalizado.")
                break

            semana = int(opcion)
            if 1 <= semana <= 8:
                df_plot = df_gantt[df_gantt['Week'] == semana].copy()
                df_plot['Inicio'] = pd.to_datetime(df_plot['Start'], unit='m', origin='2026-01-01')
                df_plot['Fin'] = pd.to_datetime(df_plot['Finish'], unit='m', origin='2026-01-01')

                fig = px.timeline(df_plot, x_start="Inicio", x_end="Fin", y="Machine", color="Piece",
                                  title=f"Diagrama de Gantt - Semana {semana} (Simulación Dinámica)",
                                  color_discrete_map={'P1':'#636EFA', 'P2':'#EF553B', 'P3':'#00CC96', 'P4':'#AB63FA'})
                fig.update_yaxes(categoryorder="array", categoryarray=["Máquina C", "Máquina B", "Máquina A"])
                fig.show()
            else:
                print("Error: Ingrese un número del 1 al 8.")
        except ValueError:
            print("Entrada no válida. Use números o 'S'.")

mostrar_menu()