# -*- coding: utf-8 -*-
"""Parcial optimizacion .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDvVB9s9f3gwz_SkN-ntyzk2Y1NP5Z-N
"""

from pulp import *

# 1. Crear el problema
prob = LpProblem("Gotham_City_Final", LpMinimize)

# 2. Variables de Decisión (Binarias)
xG1 = LpVariable("xG1", cat="Binary")
xG6 = LpVariable("xG6", cat="Binary")
sitios = [2, 3, 4, 5]
xN = {j: LpVariable(f"xN{j}", cat="Binary") for j in sitios}
xGi = {j: LpVariable(f"xGi{j}", cat="Binary") for j in sitios}
xT = {j: LpVariable(f"xT{j}", cat="Binary") for j in sitios}

# 3. Variables de Desviación
d1p = {j: LpVariable(f"d1p_{j}", 0) for j in sitios}
d2p, d2n = LpVariable("d2p", 0), LpVariable("d2n", 0)
d3p, d3n = LpVariable("d3p", 0), LpVariable("d3n", 0)

# 4. Función Objetivo (Pesos: 60%, 30%, 10%)
prob += 0.60 * lpSum(d1p[j] for j in sitios) + 0.30 * d2p + 0.10 * d3n

# 5. Restricciones Estructurales (<= 1 permite NO instalar)
prob += xG1 + xG6 <= 1
prob += lpSum(xN[j] for j in sitios) <= 1
prob += lpSum(xGi[j] for j in sitios) <= 1
prob += lpSum(xT[j] for j in sitios) <= 1

for j in sitios:
    prob += xN[j] + xGi[j] + xT[j] <= 1

# 6. Ecuaciones de Metas
terreno_cap = {2: 70, 3: 80, 4: 95, 5: 120}
for j in sitios:
    prob += (29*xN[j] + 38*xGi[j] + 45*xT[j] <= terreno_cap[j] + d1p[j])

prob += (340*(xG1 + xG6) + 300*lpSum(xN[j] for j in sitios) +
         840*lpSum(xGi[j] for j in sitios) + 85*lpSum(xT[j] for j in sitios) + d2n - d2p == 1200)

dias = {"G": {1: 31, 6: 27}, "N": {2: 25, 3: 21, 4: 32, 5: 32},
        "Gi": {2: 37, 3: 29, 4: 28, 5: 38}, "T": {2: 20, 3: 23, 4: 22, 5: 20}}

prob += (dias["G"][1]*xG1 + dias["G"][6]*xG6 + lpSum(dias["N"][j]*xN[j] for j in sitios) +
         lpSum(dias["Gi"][j]*xGi[j] for j in sitios) + lpSum(dias["T"][j]*xT[j] for j in sitios) + d3n - d3p == 200)

# 7. Resolver
prob.solve(PULP_CBC_CMD(msg=0))

# 8. Reporte Detallado
print(f"ESTADO: {LpStatus[prob.status]}")
print(f"VALOR DE Z: {value(prob.objective):.2f}\n")

print("--- UBICACIÓN DE INSTALACIONES ---")
def check_status(name, vars_list):
    found = False
    for label, var in vars_list:
        if value(var) == 1:
            print(f"  {name:10s} -> {label}")
            found = True
    if not found:
        print(f"  {name:10s} -> NO SE INSTALA")

check_status("Golf", [("Sitio 1", xG1), ("Sitio 6", xG6)])
check_status("Natacion", [(f"Sitio {j}", xN[j]) for j in sitios])
check_status("Gimnasio", [(f"Sitio {j}", xGi[j]) for j in sitios])
check_status("Tenis", [(f"Sitio {j}", xT[j]) for j in sitios])

print("\n--- ANÁLISIS DE METAS ---")
# Cálculo de cumplimiento
exceso_presu = value(d2p)
deficit_dias = value(d3n)
exceso_terr = sum(value(d1p[j]) for j in sitios)

print(f"1. Terreno (Peso 60%): Exceso de {exceso_terr} ft2.  Impacto en Z: {exceso_terr * 0.60:.2f}")
print(f"2. Presupuesto (30%): Exceso de {exceso_presu} USD. Impacto en Z: {exceso_presu * 0.30:.2f}")
print(f"3. Días-Usuario (10%): Déficit de {deficit_dias} unidades. Impacto en Z: {deficit_dias * 0.10:.2f}")

print(f"\nSuma de impactos: {exceso_terr*0.6 + exceso_presu*0.3 + deficit_dias*0.1:.2f} (Igual a Z)")